import { useEffect, useState, type Dispatch, type FormEvent, type SetStateAction } from 'react'
import { ListMusic, Package, Plus, Trash2, UserRound } from 'lucide-react'
import { listResource, saveResource } from './data'
import { createId, type BandMaterial, type BandPerson, type PersonKind, type SetlistTemplate } from './model'

const kindLabels: Record<PersonKind, string> = { musica: 'Música', tecnic: 'Tècnic', manager: 'Mànager', contacte: 'Contacte' }

export default function BandResources() {
  const [people, setPeople] = useState<BandPerson[]>([])
  const [materials, setMaterials] = useState<BandMaterial[]>([])
  const [setlists, setSetlists] = useState<SetlistTemplate[]>([])
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [person, setPerson] = useState({ name: '', kind: 'musica' as PersonKind, phone: '', email: '' })
  const [material, setMaterial] = useState({ name: '', category: '' })
  const [setlist, setSetlist] = useState({ name: '', songs: '' })

  useEffect(() => { let active = true; Promise.all([listResource<BandPerson>('band_people'), listResource<BandMaterial>('band_materials'), listResource<SetlistTemplate>('setlist_templates')]).then(([p, m, s]) => { if (active) { setPeople(p); setMaterials(m); setSetlists(s) } }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : 'No s’han pogut carregar els recursos.') }); return () => { active = false } }, [])
  async function addPerson(event: FormEvent) { event.preventDefault(); await addResource<BandPerson>('band_people', { id: createId(), ...person, active: true }, setPeople); setPerson({ name: '', kind: 'musica', phone: '', email: '' }) }
  async function addMaterial(event: FormEvent) { event.preventDefault(); await addResource<BandMaterial>('band_materials', { id: createId(), ...material, active: true }, setMaterials); setMaterial({ name: '', category: '' }) }
  async function addSetlist(event: FormEvent) { event.preventDefault(); await addResource<SetlistTemplate>('setlist_templates', { id: createId(), name: setlist.name, songs: setlist.songs.split('\n').map((song) => song.trim()).filter(Boolean), active: true }, setSetlists); setSetlist({ name: '', songs: '' }) }
  async function addResource<T extends BandPerson | BandMaterial | SetlistTemplate>(table: 'band_people' | 'band_materials' | 'setlist_templates', value: T, setter: Dispatch<SetStateAction<T[]>>) { setBusy(true); setError(''); try { const saved = await saveResource(table, value); setter((items) => [...items, saved]) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No s’ha pogut desar el recurs.') } finally { setBusy(false) } }
  async function archive<T extends BandPerson | BandMaterial | SetlistTemplate>(table: 'band_people' | 'band_materials' | 'setlist_templates', item: T, setter: Dispatch<SetStateAction<T[]>>) { setBusy(true); try { await saveResource(table, { ...item, active: false }); setter((items) => items.filter((entry) => entry.id !== item.id)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No s’ha pogut arxivar el recurs.') } finally { setBusy(false) } }

  return <div className="resources-shell"><div className="page-heading resources-heading"><div><span className="eyebrow">RECURSOS DE LA BANDA</span><h1>Equip, material i repertori<span className="heading-period">.</span></h1><p>Defineix una vegada allò que reutilitzes i tria-ho després a cada concert.</p></div></div><div className="resources-grid">
    <section className="form-card resource-card"><div className="section-heading"><span className="section-index"><UserRound size={16} /></span><div><h2>Persones i equip</h2><p>Qui pot participar en un concert.</p></div></div><form className="fields" onSubmit={(event) => void addPerson(event)}><label className="field">Nom <input required value={person.name} onChange={(event) => setPerson({ ...person, name: event.target.value })} placeholder="Nom i cognoms" /></label><div className="two-col"><label className="field">Tipus <select value={person.kind} onChange={(event) => setPerson({ ...person, kind: event.target.value as PersonKind })}>{Object.entries(kindLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field">Telèfon <input value={person.phone} onChange={(event) => setPerson({ ...person, phone: event.target.value })} /></label></div><label className="field">Correu <input type="email" value={person.email} onChange={(event) => setPerson({ ...person, email: event.target.value })} /></label><button className="button button-primary" disabled={busy}><Plus size={15} /> Afegir persona</button></form><div className="resource-list">{people.map((item) => <div className="resource-row" key={item.id}><div><strong>{item.name}</strong><small>{kindLabels[item.kind]}{item.phone ? ` · ${item.phone}` : ''}</small></div><button className="icon-button" type="button" disabled={busy} onClick={() => void archive('band_people', item, setPeople)}><Trash2 size={14} /></button></div>)}</div></section>
    <section className="form-card resource-card"><div className="section-heading"><span className="section-index"><Package size={16} /></span><div><h2>Material del grup</h2><p>La base per preparar cada càrrega.</p></div></div><form className="fields" onSubmit={(event) => void addMaterial(event)}><label className="field">Material <input required value={material.name} onChange={(event) => setMaterial({ ...material, name: event.target.value })} placeholder="Micròfon, pedalera…" /></label><label className="field">Categoria <input value={material.category} onChange={(event) => setMaterial({ ...material, category: event.target.value })} placeholder="So, instruments, marxandatge…" /></label><button className="button button-primary" disabled={busy}><Plus size={15} /> Afegir material</button></form><div className="resource-list">{materials.map((item) => <div className="resource-row" key={item.id}><div><strong>{item.name}</strong><small>{item.category || 'Sense categoria'}</small></div><button className="icon-button" type="button" disabled={busy} onClick={() => void archive('band_materials', item, setMaterials)}><Trash2 size={14} /></button></div>)}</div></section>
    <section className="form-card resource-card"><div className="section-heading"><span className="section-index"><ListMusic size={16} /></span><div><h2>Plantilles de setlist</h2><p>Repertoris que després pots ajustar per concert.</p></div></div><form className="fields" onSubmit={(event) => void addSetlist(event)}><label className="field">Nom de la plantilla <input required value={setlist.name} onChange={(event) => setSetlist({ ...setlist, name: event.target.value })} placeholder="Setlist festival" /></label><label className="field">Cançons <textarea required rows={5} value={setlist.songs} onChange={(event) => setSetlist({ ...setlist, songs: event.target.value })} placeholder="Una cançó per línia" /></label><button className="button button-primary" disabled={busy}><Plus size={15} /> Afegir plantilla</button></form><div className="resource-list">{setlists.map((item) => <div className="resource-row" key={item.id}><div><strong>{item.name}</strong><small>{item.songs.length} cançons</small></div><button className="icon-button" type="button" disabled={busy} onClick={() => void archive('setlist_templates', item, setSetlists)}><Trash2 size={14} /></button></div>)}</div></section>
  </div>{error ? <div className="global-error" role="alert">{error}</div> : null}</div>
}
