import { useEffect, useState, type FormEvent } from 'react'
import { Package, Plus, Trash2 } from 'lucide-react'
import { listResource, saveResource } from './data'
import { createId, type BandMaterial } from './model'

export default function BandMaterials() {
  const [materials, setMaterials] = useState<BandMaterial[]>([])
  const [material, setMaterial] = useState({ name: '', category: '' })
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  useEffect(() => { let active = true; listResource<BandMaterial>('band_materials').then((items) => { if (active) setMaterials(items) }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : 'No s’ha pogut carregar el material.') }); return () => { active = false } }, [])
  async function add(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const saved = await saveResource('band_materials', { id: createId(), ...material, active: true }); setMaterials((items) => [...items, saved]); setMaterial({ name: '', category: '' }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No s’ha pogut desar el material.') } finally { setBusy(false) } }
  async function archive(item: BandMaterial) { setBusy(true); setError(''); try { await saveResource('band_materials', { ...item, active: false }); setMaterials((items) => items.filter((entry) => entry.id !== item.id)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No s’ha pogut arxivar el material.') } finally { setBusy(false) } }
  const categories = Array.from(new Set(materials.map((item) => item.category || 'Sense categoria')))
  return <div className="resource-page"><div className="page-heading resources-heading"><div><span className="eyebrow">MATERIAL DE LA BANDA</span><h1>El que ha de pujar a l’escenari<span className="heading-period">.</span></h1><p>Construeix el catàleg habitual i tria la càrrega de cada concert des de la seva fitxa.</p></div></div><div className="resource-layout"><section className="form-card resource-add-card"><div className="section-heading"><span className="section-index"><Package size={16} /></span><div><h2>Afegir material</h2><p>Un element del catàleg reutilitzable.</p></div></div><form className="fields" onSubmit={(event) => void add(event)}><label className="field">Material <input required value={material.name} onChange={(event) => setMaterial({ ...material, name: event.target.value })} placeholder="Micròfon, pedalera…" /></label><label className="field">Categoria <input value={material.category} onChange={(event) => setMaterial({ ...material, category: event.target.value })} placeholder="So, instruments, marxandatge…" /></label><button className="button button-primary" disabled={busy}><Plus size={15} /> Afegir material</button></form></section><div className="resource-groups">{categories.length ? categories.map((category) => <section className="resource-group" key={category}><div className="resource-group-heading"><div><span className="eyebrow">{materials.filter((item) => (item.category || 'Sense categoria') === category).length} ELEMENTS</span><h2>{category}</h2></div></div><div className="resource-list">{materials.filter((item) => (item.category || 'Sense categoria') === category).map((item) => <div className="resource-row" key={item.id}><div><strong>{item.name}</strong><small>Disponible per afegir a un concert</small></div><button className="icon-button" type="button" disabled={busy} aria-label={`Arxivar ${item.name}`} onClick={() => void archive(item)}><Trash2 size={14} /></button></div>)}</div></section>) : <section className="resource-group"><p className="section-empty">Encara no hi ha material al catàleg.</p></section>}</div></div>{error ? <div className="global-error" role="alert">{error}</div> : null}</div>
}
